#User
GET http://localhost:3030/Users/

###

GET http://localhost:3030/Users/65785a83c81422c5b875f416


###


POST http://localhost:3000/Users/
Content-Type: application/json

{
  "email": "newuser3@example.com",
  "password": "newuser3",
  "phone_number": "+26262626262",
  "name": "tasnim",
  "profile_picture": "https://example.com/profile_picture3.jpg",
  "verification_status": true,
  "user_type": "driver"
}

###

DELETE http://localhost:3000/Users/656487c2f8e8bab85b1ee760


###


PATCH  http://localhost:3000/Users/656487c2f8e8bab85b1ee760
Content-Type: application/json

{
    "phone_number": "+2"
}

###

POST http://localhost:3000/Users/search
Content-Type: application/json

{
    "searchTerm": "y"
}

###

POST http://localhost:3000/Users/login
Content-Type: application/json

{
  "username": "newuser1@example.com",
  "password": "newuse1rpassword"
}


###

#Ride
GET http://localhost:3000/Rides/

###

GET http://localhost:3000/Rides/price/low-high

###

GET http://localhost:3000/Rides/price/high-low

###

GET http://localhost:3000/Rides/expired/65638198fc8cbd7c791ed74d

###

GET http://localhost:3000/Rides/available/65638198fc8cbd7c791ed74d

###

GET http://localhost:3000/Rides/65737be8667c94eac47fec63

###

GET http://localhost:3000/Rides/filter/65638198fc8cbd7c791ed74d

###

POST http://localhost:3000/Rides/
Content-Type: application/json

{
  "driver_id": "65638198fc8cbd7c791ed74d",
  "car_brand": "clio peugeot 106",
  "start_location": "Tunis",
  "end_location": "Sousse",
  "departure_time": "2023-12-11T14:00:00",
  "arrival_time": "2023-12-11T16:00:00",
  "available_seats": 3,
  "price_per_seat": 14,
  "ride_description": "Morning commute from Tunis to Sousse."
}

###

POST http://localhost:3030/Rides/location
Content-Type: application/json

{
  "departure":"",
  "destination":"",
  "day":"",
  "passengers":""
}

###

POST http://localhost:3000/Reservations/
Content-Type: application/json

{
  "passenger_id": "65638198fc8cbd7c791ed74d",
  "ride_id": "657387d7a88f33298dfdeb9f",
  "reserved_seats": "5",
  "reservation_status": "confirmed"
}